name: Build luci-app-sms-tool

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    # -------------------------- 步骤 1：拉取代码 --------------------------
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive  # 确保拉取所有子模块

    # -------------------------- 步骤 2：安装基础依赖 --------------------------
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3 unzip rsync p7zip-full

    # -------------------------- 步骤 3：合并分块文件 --------------------------
    - name: Merge split files
      run: |
        # 合并所有分块文件
        cat openwrt-sdk-source.tar.xz.* > openwrt-sdk-source.tar.xz
        # 检查合并后的文件
        ls -lh openwrt-sdk-source.tar.xz

    # -------------------------- 步骤 4：解压并修复权限 --------------------------
    - name: Extract SDK and fix permissions
      run: |
        # 创建目标目录
        mkdir -p sdk-source
        # 解压 SDK
        tar -xf openwrt-sdk-source.tar.xz -C sdk-source/
        # 重命名目录（根据实际解压后的目录名调整）
        mv sdk-source/openwrt-22.03.7 sdk-source/openwrt-sdk
        # 递归修复权限（关键！）
        chmod -R a+x sdk-source/openwrt-sdk/scripts
        chmod -R a+x sdk-source/openwrt-sdk/feeds

    # -------------------------- 步骤 5：复制项目文件到 SDK --------------------------
    - name: Copy project files
      run: |
        # 创建目标目录
        mkdir -p sdk-source/openwrt-sdk/package/luci-app-sms-tool
        # 复制源码（假设项目文件在仓库根目录）
        cp -r $GITHUB_WORKSPACE/* sdk-source/openwrt-sdk/package/luci-app-sms-tool/

    # -------------------------- 步骤 6：编译 LuCI 应用 --------------------------
    - name: Compile luci-app-sms-tool
      run: |
        cd sdk-source/openwrt-sdk
        # 更新 feeds
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        # 生成默认配置
        make defconfig
        # 开始编译（显示详细日志）
        make package/luci-app-sms-tool/compile V=s

    # -------------------------- 步骤 7：上传生成的 IPK 文件 --------------------------
    - name: Upload IPK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipk-package
        path: sdk-source/openwrt-sdk/bin/packages/x86_64/luci/*.ipk
