name: Build luci-app-sms-tool

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    # -------------------------- 步骤 1：拉取代码 --------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------- 步骤 2：安装依赖 --------------------------
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full build-essential python3 xz-utils

    # -------------------------- 步骤 3：合并并解压分块文件（两层解压） --------------------------
    - name: Merge and extract SDK
      run: |
        # 合并 7z 分块文件
        7z x openwrt-sdk-source.7z.001 -o./_temp

        # 二次解压内部的 tar.xz 文件
        mkdir -p sdk-source
        tar -xf _temp/openwrt-sdk-source.tar.xz -C sdk-source/

        # 调试：展示解压后的目录结构
        echo "===== SDK 目录结构 ====="
        ls -l sdk-source/

        # 动态获取 SDK 目录名（示例：openwrt-22.03.7）
        SDK_DIR_NAME=$(ls sdk-source)
        mv sdk-source/$SDK_DIR_NAME sdk-source/openwrt-sdk

        # 清理临时文件
        rm -rf _temp

    # -------------------------- 步骤 4：修复权限 --------------------------
    - name: Fix permissions
      run: |
        cd sdk-source/openwrt-sdk
        chmod -R +x scripts
        chmod -R +x feeds

    # -------------------------- 步骤 5：复制项目文件 --------------------------
    - name: Copy project files
      run: |
        mkdir -p sdk-source/openwrt-sdk/package/luci-app-sms-tool
        cp -r $GITHUB_WORKSPACE/* sdk-source/openwrt-sdk/package/luci-app-sms-tool/

    # -------------------------- 步骤 6：编译 LuCI 应用 --------------------------
    - name: Compile luci-app-sms-tool
      run: |
        cd sdk-source/openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/luci-app-sms-tool/compile V=s

    # -------------------------- 步骤 7：上传生成的 IPK 文件 --------------------------
    - name: Upload IPK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipk-package
        path: sdk-source/openwrt-sdk/bin/packages/x86_64/luci/*.ipk
