name: Build luci-app-sms-tool

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    # -------------------------- 步骤 1：拉取代码 --------------------------
    - name: Checkout code
      uses: actions/checkout@v4

    # -------------------------- 步骤 2：安装依赖 --------------------------
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full build-essential python3

    # -------------------------- 步骤 3：合并并解压 7z 分块文件 --------------------------
    - name: Merge and extract 7z split files
      run: |
        # 合并并解压分块文件到临时目录
        7z x openwrt-sdk-source.7z.001 -o./_temp_sdk

        # 调试：展示解压后的文件结构（关键！）
        echo "===== 解压后的文件结构 ====="
        ls -l _temp_sdk

        # 检查解压内容是否为目录（动态适配）
        if [ -d "_temp_sdk/openwrt-sdk" ]; then
          mv _temp_sdk/openwrt-sdk sdk-source
        elif [ -d "_temp_sdk/openwrt-22.03.7" ]; then
          mv _temp_sdk/openwrt-22.03.7 sdk-source/openwrt-sdk
        else
          echo "错误：解压后的内容不是有效目录"
          exit 1
        fi

        # 清理临时目录
        rm -rf _temp_sdk

    # -------------------------- 步骤 4：修复权限 --------------------------
    - name: Fix permissions
      run: |
        cd sdk-source/openwrt-sdk
        chmod -R +x scripts
        chmod -R +x feeds

    # -------------------------- 步骤 5：复制项目文件 --------------------------
    - name: Copy project files
      run: |
        mkdir -p sdk-source/openwrt-sdk/package/luci-app-sms-tool
        cp -r $GITHUB_WORKSPACE/* sdk-source/openwrt-sdk/package/luci-app-sms-tool/

    # -------------------------- 步骤 6：编译 LuCI 应用 --------------------------
    - name: Compile luci-app-sms-tool
      run: |
        cd sdk-source/openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/luci-app-sms-tool/compile V=s

    # -------------------------- 步骤 7：上传生成的 IPK 文件 --------------------------
    - name: Upload IPK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipk-package
        path: sdk-source/openwrt-sdk/bin/packages/x86_64/luci/*.ipk
