name: Build luci-app-sms-tool

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify split files
      run: |
        if [ ! -f openwrt-sdk-source.7z.001 ]; then
          echo "错误：分块文件 openwrt-sdk-source.7z.001 不存在"
          exit 1
        fi
        echo "分块文件验证通过"

    - name: Install 7-Zip and merge files
      run: |
        sudo apt-get install -y p7zip-full
        ls -l  # 调试文件列表
        7z x openwrt-sdk-source.7z.001 -o./sdk-source

    - name: Set up OpenWrt SDK
      run: |
        cd sdk-source
        tar -xf openwrt-sdk-source.tar.xz
        mv openwrt openwrt-sdk

    - name: Compile luci-app-sms-tool
      run: |
        cd sdk-source/openwrt-sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig
        make package/luci-app-sms-tool/compile V=s

    - name: Upload IPK artifact
      uses: actions/upload-artifact@v4
      with:
        name: ipk-package
        path: sdk-source/openwrt-sdk/bin/packages/x86_64/luci/*.ipk
